version: 2.1

jobs:
  build:
    docker:
      - image: yzouad/ubuntu_18.04_yocto:v1
        environment:
          LC_ALL: en_US.UTF-8
          LANG: en_US.UTF-8
          LANGUAGE: en_US.UTF-8
    steps:
      - checkout
      - run:
          name: Get helper-scripts
          command: |
                git clone https://github.com/yzouad-christ/jenkins-yocto.git /home/builder/jenkins-yocto
                cd /home/builder/jenkins-yocto
                git checkout circleci-project-setup
                chmod -R a+x /home/builder/jenkins-yocto
      - run:
          name: Clone ces-bsp-platform
          command: |
                git config --global user.email "yzouad@yzouad.com"
                git config --global user.name "yzouad"
                mkdir /home/builder/ces-bsp-platform
                cd /home/builder/ces-bsp-platform
                repo init -u https://github.com/software-celo/ces-bsp-platform -b warrior
                repo sync
      - run:
          name: Build ces-qt-demoimage (pixi-cdl100)
          command: |
                cd /home/builder/jenkins-yocto
                ./execBitbake.sh "/home/builder" "pixi-cdl100" "ces-fb" "ces-qt-demoimage"

      - run:
          name: Build ces-qt-demoimage (crix-cql100)
          command: |
                MACHINE=crix-cq100 
                DISTRO=ces-fb
                yes | source /home/builder/ces-bsp-platform/setup-environment build
                bitbake ces-qt-demoimage


workflows:
  workflow:
    jobs:
      - build
